version: "3.10"

services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-library}
    ports:
      - "5432:5432"
    networks:
      library_network:
  app:
    image: library-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /usr/src/app/static
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db/library}
    depends_on:
      - db
      - redis
    restart: always
    networks:
      library_network:
        aliases:
          - library-back.local
          - www.library-back.local

  redis:
    image: redis:6.2.6-alpine
    networks:
      library_network:

volumes:
  postgres-db-volume:

networks:
    library_network:
        name: 'library'